[package]
name = "sequents"
version = "0.1.1"
edition = "2024"
description = "Multiplicative-additive linear System L with exponentials, embedded in Rust's type system"
license = "BSD-3-Clause"
homepage = "https://git.sr.ht/~lane/sequents"
repository = "https://git.sr.ht/~lane/sequents"
documentation = "https://docs.rs/sequents"
keywords = ["linear-logic", "sequent-calculus", "lambda-mu", "type-system"]
categories = ["no-std", "science"]
include = [
  "Cargo.toml",
  "Cargo.lock",
  "LICENSE",
  "README.md",
  ".gitignore",
  "src/*.rs",
  "tests/*.rs",
  "docs/*.md",
  "docs/*.bib",
]

[dependencies]
